### ISSUE TITLE
Failed to retrieve pre-login tokens

### ISSUE THREAD

**Issue by 0xHal** [zSoulweaver/kient#7] opened 2024-02-28 21:09 UTC
Has kick updated their API?
I'm not able to connect no more, didn't changed anything in the code.
![image](https://github.com/zSoulweaver/kient/assets/134301949/aed10640-8578-49a4-8265-a56050e2120f)

Error is triggered in the getTokenks() function, but don't know why.
![image](https://github.com/zSoulweaver/kient/assets/134301949/1c16516a-01e9-48b0-b0e9-85ce801eead6)

**Comment by c0uldfusi0n** [comment] 2024-02-29 20:59
You probably need the x-kick-auth

**Comment by 0xHal** [comment] 2024-02-29 21:17
> You probably need the x-kick-auth
If by x-kick-auth you mean totp it's okay:
![image](https://github.com/zSoulweaver/kient/assets/134301949/3b6d1c0d-f0a5-4a31-9759-523bbed7c445)

By the way, it doesn't return anything as it say in the docs.

**Comment by zSoulweaver** [comment] 2024-02-29 22:19
I will look into this over the weekend. Have been away on holiday this past week without access to a computer.

**Comment by c0uldfusi0n** [comment] 2024-02-29 22:21
refering to [this](https://github.com/zSoulweaver/kient/pull/6) 
something like:
`const login = await client.api.authentication.login({
    email: process.env.EMAIL,
    password: process.env.PASSWORD,
    otc: OTP
  }, process.env.KICK_AUTH);`

**Comment by zSoulweaver** [comment] 2024-02-29 22:23
> You probably need the x-kick-auth

I believe this is only provided to some lucky folk who have been whitelisted against the API to bypass CloudFlare. Us plebs have to work around it unfortunately.

**Comment by c0uldfusi0n** [comment] 2024-02-29 22:25
> > You probably need the x-kick-auth
> 
> I believe this is only provided to some lucky folk who have been whitelisted against the API to bypass CloudFlare. Us plebs have to work around it unfortunately.

true but even with it u get rate limited by kick =)

**Comment by zSoulweaver** [comment] 2024-03-01 10:44
I'm struggling to reproduce this on my local machine, @0xHal.

The "Just a moment..." title tag in the body that is being returned in the error would indicate that you are hitting the Cloudflare block. Could be a number of different things, but I don't believe it is an error on Kient's side.

**Comment by 0xHal** [comment] 2024-03-01 15:00
> I'm struggling to reproduce this on my local machine, @0xHal.
> 
> The "Just a moment..." title tag in the body that is being returned in the error would indicate that you are hitting the Cloudflare block. Could be a number of different things, but I don't believe it is an error on Kient's side.

Yes exactly!
Thanks for all your work man!
If you have any donation link i will be happy to send you some money (i'm not rich ^^)

**Comment by b3ck** [comment] 2024-04-02 18:26
stopped my script and started it back up again and getting this error:

<img width="577" alt="Screen Shot 2024-04-02 at 1 24 22 PM" src="https://github.com/zSoulweaver/kient/assets/1740542/2fe09ce3-edbc-43ac-ad59-07cf70c88a0b">

Seems to be the same error as above, any ideas?

**Comment by zSoulweaver** [comment] 2024-10-21 11:21
Unfortunately, nothing much further can really be done do avoid Cloudflare at the present point. Kient will be rewritten for the public API when available.

Proxy support #25 has just been merged in which should help somewhat.

**Closed by zSoulweaver** 2024-10-21 11:21 UTC
